sudo: required
language: generic
services: 
  - docker

before_install:
  - docker build -t souravpcs/docker-react -f Dockerfile.dev .

scripts:
  - docker run souravpcs/docker-react npm run test -- --coverage
